ci:
  autofix_commit_msg: "格式化代码"
  autofix_prs: true
  autoupdate_branch: main

repos:
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: [--select=E9]
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        args: []
  - repo: https://github.com/python-poetry/poetry
    rev: '2.0.1'
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args: ["--regenerate"]
      - id: poetry-install